import { Knex } from "knex";
import { constants, enums } from "@lib";
const { TableName } = constants

const { MembershipTypeEnum } = enums
export async function seed(knex: Knex): Promise<void> {
	// remove all existing entries
	// await knex('Customers').del();

	const customers = [
		{
			oldCustomerId: 'CUST-0001',
			// userId: 101,
			deleteFlag: false,
			email: 'alice.smith@example.com',
			accountName: 'alice.smith',
			firstName: 'Alice',
			middleName: 'M',
			lastName: 'Smith',
			mobilePhone: '+628111000001',
			membershipType: MembershipTypeEnum.Standard,
			byEmail: true,
			byPost: false,
			byWhatsapp: true,
			byFacebookMessenger: false,
			bySms: true,
			byTelephone: false,
		},
		{
			oldCustomerId: 'CUST-0002',
			// userId: 102,
			deleteFlag: false,
			email: 'bob.johnson@example.com',
			accountName: 'bobj',
			firstName: 'Bob',
			middleName: '',
			lastName: 'Johnson',
			mobilePhone: '+628111000002',
			membershipType: MembershipTypeEnum.Standard,
			byEmail: false,
			byPost: false,
			byWhatsapp: false,
			byFacebookMessenger: false,
			bySms: true,
			byTelephone: false,
		},
		{
			oldCustomerId: 'CUST-0003',
			// userId: 103,
			deleteFlag: false,
			email: 'carol.wu@example.com',
			accountName: 'carolw',
			firstName: 'Carol',
			middleName: 'A',
			lastName: 'Wu',
			mobilePhone: '+628111000003',
			membershipType: MembershipTypeEnum.Standard,
			byEmail: true,
			byPost: true,
			byWhatsapp: false,
			byFacebookMessenger: false,
			bySms: false,
			byTelephone: true,
		},
		{
			oldCustomerId: 'CUST-0004',
			// userId: 104,
			deleteFlag: false,
			email: 'david.lee@example.com',
			accountName: 'davidlee',
			firstName: 'David',
			middleName: '',
			lastName: 'Lee',
			mobilePhone: '+628111000004',
			membershipType: MembershipTypeEnum.Standard,
			byEmail: true,
			byPost: false,
			byWhatsapp: true,
			byFacebookMessenger: true,
			bySms: true,
			byTelephone: false,
		},
		{
			oldCustomerId: 'CUST-0005',
			// userId: 105,
			deleteFlag: false,
			email: 'emma.khan@example.com',
			accountName: 'emmak',
			firstName: 'Emma',
			middleName: 'R',
			lastName: 'Khan',
			mobilePhone: '+628111000005',
			membershipType: MembershipTypeEnum.Standard,
			byEmail: false,
			byPost: true,
			byWhatsapp: false,
			byFacebookMessenger: false,
			bySms: false,
			byTelephone: false,
		},
		{
			oldCustomerId: 'CUST-0006',
			// userId: 106,
			deleteFlag: false,
			email: 'frank.miller@example.com',
			accountName: 'frankm',
			firstName: 'Frank',
			middleName: '',
			lastName: 'Miller',
			mobilePhone: '+628111000006',
			membershipType: MembershipTypeEnum.Standard,
			byEmail: true,
			byPost: false,
			byWhatsapp: false,
			byFacebookMessenger: false,
			bySms: true,
			byTelephone: true,
		},
		{
			oldCustomerId: 'CUST-0007',
			// userId: 107,
			deleteFlag: false,
			email: 'gina.patel@example.com',
			accountName: 'ginap',
			firstName: 'Gina',
			middleName: 'L',
			lastName: 'Patel',
			mobilePhone: '+628111000007',
			membershipType: MembershipTypeEnum.Standard,
			byEmail: false,
			byPost: false,
			byWhatsapp: true,
			byFacebookMessenger: false,
			bySms: false,
			byTelephone: false,
		},
		{
			oldCustomerId: 'CUST-0008',
			// userId: 108,
			deleteFlag: false,
			email: 'henry.owen@example.com',
			accountName: 'henryo',
			firstName: 'Henry',
			middleName: '',
			lastName: 'Owen',
			mobilePhone: '+628111000008',
			membershipType: MembershipTypeEnum.Standard,
			byEmail: true,
			byPost: false,
			byWhatsapp: true,
			byFacebookMessenger: false,
			bySms: true,
			byTelephone: false,
		},
		{
			oldCustomerId: 'CUST-0009',
			// userId: 109,
			deleteFlag: false,
			email: 'irene.lopez@example.com',
			accountName: 'irenel',
			firstName: 'Irene',
			middleName: 'S',
			lastName: 'Lopez',
			mobilePhone: '+628111000009',
			membershipType: MembershipTypeEnum.Standard,
			byEmail: false,
			byPost: false,
			byWhatsapp: false,
			byFacebookMessenger: true,
			bySms: false,
			byTelephone: false,
		},
		{
			oldCustomerId: 'CUST-0010',
			// userId: 110,
			deleteFlag: false,
			email: 'jack.chen@example.com',
			accountName: 'jackc',
			firstName: 'Jack',
			middleName: '',
			lastName: 'Chen',
			mobilePhone: '+628111000010',
			membershipType: MembershipTypeEnum.Standard,
			byEmail: false,
			byPost: false,
			byWhatsapp: false,
			byFacebookMessenger: false,
			bySms: false,
			byTelephone: false,
		},
	];

	await knex(TableName.Customers).insert(customers);
}