import { Knex } from "knex";
import { constants, enums } from "@lib";
const { TableName } = constants

const { MembershipTypeEnum } = enums
export async function seed(knex: Knex): Promise<void> {
	// remove all existing entries
	// await knex('customers').del();

	const customers = [
		{
			old_customer_id: 'CUST-0001',
			// user_id: 101,
			delete_flag: false,
			email: 'alice.smith@example.com',
			account_name: 'alice.smith',
			first_name: 'Alice',
			middle_name: 'M',
			last_name: 'Smith',
			mobile_phone: '+628111000001',
			membership_type: MembershipTypeEnum.Standard,
			multi_factor_athentication: true,
			otp_code_attempt: 0,
			otp_code: null,
			qr_otp_code: null,
			login_attempts: 0,
			lock_until: null,
			// last_login: new Date('2025-12-01'),
			by_email: true,
			by_post: false,
			by_whatsapp: true,
			by_facebook_messenger: false,
			by_sms: true,
			by_telephone: false,
		},
		{
			old_customer_id: 'CUST-0002',
			// user_id: 102,
			delete_flag: false,
			email: 'bob.johnson@example.com',
			account_name: 'bobj',
			first_name: 'Bob',
			middle_name: '',
			last_name: 'Johnson',
			mobile_phone: '+628111000002',
			membership_type: MembershipTypeEnum.Standard,
			multi_factor_athentication: false,
			otp_code_attempt: 1,
			otp_code: '123456',
			qr_otp_code: null,
			login_attempts: 1,
			lock_until: null,
			// last_login: new Date('2025-11-20'),
			by_email: false,
			by_post: false,
			by_whatsapp: false,
			by_facebook_messenger: false,
			by_sms: true,
			by_telephone: false,
		},
		{
			old_customer_id: 'CUST-0003',
			// user_id: 103,
			delete_flag: false,
			email: 'carol.wu@example.com',
			account_name: 'carolw',
			first_name: 'Carol',
			middle_name: 'A',
			last_name: 'Wu',
			mobile_phone: '+628111000003',
			membership_type: MembershipTypeEnum.Standard,
			multi_factor_athentication: false,
			otp_code_attempt: 0,
			otp_code: null,
			qr_otp_code: null,
			login_attempts: 0,
			lock_until: null,
			// last_login: null,
			by_email: true,
			by_post: true,
			by_whatsapp: false,
			by_facebook_messenger: false,
			by_sms: false,
			by_telephone: true,
		},
		{
			old_customer_id: 'CUST-0004',
			// user_id: 104,
			delete_flag: false,
			email: 'david.lee@example.com',
			account_name: 'davidlee',
			first_name: 'David',
			middle_name: '',
			last_name: 'Lee',
			mobile_phone: '+628111000004',
			membership_type: MembershipTypeEnum.Standard,
			multi_factor_athentication: true,
			otp_code_attempt: 2,
			otp_code: '654321',
			qr_otp_code: 'QR123',
			login_attempts: 2,
			lock_until: new Date('2025-12-31'),
			// last_login: new Date('2025-12-10'),
			by_email: true,
			by_post: false,
			by_whatsapp: true,
			by_facebook_messenger: true,
			by_sms: true,
			by_telephone: false,
		},
		{
			old_customer_id: 'CUST-0005',
			// user_id: 105,
			delete_flag: false,
			email: 'emma.khan@example.com',
			account_name: 'emmak',
			first_name: 'Emma',
			middle_name: 'R',
			last_name: 'Khan',
			mobile_phone: '+628111000005',
			membership_type: MembershipTypeEnum.Standard,
			multi_factor_athentication: false,
			otp_code_attempt: 0,
			otp_code: null,
			qr_otp_code: null,
			login_attempts: 0,
			lock_until: null,
			// last_login: new Date('2025-10-05'),
			by_email: false,
			by_post: true,
			by_whatsapp: false,
			by_facebook_messenger: false,
			by_sms: false,
			by_telephone: false,
		},
		{
			old_customer_id: 'CUST-0006',
			// user_id: 106,
			delete_flag: false,
			email: 'frank.miller@example.com',
			account_name: 'frankm',
			first_name: 'Frank',
			middle_name: '',
			last_name: 'Miller',
			mobile_phone: '+628111000006',
			membership_type: MembershipTypeEnum.Standard,
			multi_factor_athentication: false,
			otp_code_attempt: 3,
			otp_code: '000999',
			qr_otp_code: null,
			login_attempts: 3,
			lock_until: null,
			// last_login: new Date('2025-09-15'),
			by_email: true,
			by_post: false,
			by_whatsapp: false,
			by_facebook_messenger: false,
			by_sms: true,
			by_telephone: true,
		},
		{
			old_customer_id: 'CUST-0007',
			// user_id: 107,
			delete_flag: false,
			email: 'gina.patel@example.com',
			account_name: 'ginap',
			first_name: 'Gina',
			middle_name: 'L',
			last_name: 'Patel',
			mobile_phone: '+628111000007',
			membership_type: MembershipTypeEnum.Standard,
			multi_factor_athentication: false,
			otp_code_attempt: 0,
			otp_code: null,
			qr_otp_code: null,
			login_attempts: 0,
			lock_until: null,
			// last_login: null,
			by_email: false,
			by_post: false,
			by_whatsapp: true,
			by_facebook_messenger: false,
			by_sms: false,
			by_telephone: false,
		},
		{
			old_customer_id: 'CUST-0008',
			// user_id: 108,
			delete_flag: false,
			email: 'henry.owen@example.com',
			account_name: 'henryo',
			first_name: 'Henry',
			middle_name: '',
			last_name: 'Owen',
			mobile_phone: '+628111000008',
			membership_type: MembershipTypeEnum.Standard,
			multi_factor_athentication: true,
			otp_code_attempt: 0,
			otp_code: null,
			qr_otp_code: 'QR998',
			login_attempts: 0,
			lock_until: null,
			// last_login: new Date('2025-12-12'),
			by_email: true,
			by_post: false,
			by_whatsapp: true,
			by_facebook_messenger: false,
			by_sms: true,
			by_telephone: false,
		},
		{
			old_customer_id: 'CUST-0009',
			// user_id: 109,
			delete_flag: false,
			email: 'irene.lopez@example.com',
			account_name: 'irenel',
			first_name: 'Irene',
			middle_name: 'S',
			last_name: 'Lopez',
			mobile_phone: '+628111000009',
			membership_type: MembershipTypeEnum.Standard,
			multi_factor_athentication: false,
			otp_code_attempt: 0,
			otp_code: null,
			qr_otp_code: null,
			login_attempts: 0,
			lock_until: null,
			// last_login: new Date('2025-08-01'),
			by_email: false,
			by_post: false,
			by_whatsapp: false,
			by_facebook_messenger: true,
			by_sms: false,
			by_telephone: false,
		},
		{
			old_customer_id: 'CUST-0010',
			// user_id: 110,
			delete_flag: false,
			email: 'jack.chen@example.com',
			account_name: 'jackc',
			first_name: 'Jack',
			middle_name: '',
			last_name: 'Chen',
			mobile_phone: '+628111000010',
			membership_type: MembershipTypeEnum.Standard,
			multi_factor_athentication: false,
			otp_code_attempt: 0,
			otp_code: null,
			qr_otp_code: null,
			login_attempts: 0,
			lock_until: null,
			// last_login: null,
			by_email: false,
			by_post: false,
			by_whatsapp: false,
			by_facebook_messenger: false,
			by_sms: false,
			by_telephone: false,
		},
	];

	await knex(TableName.Customers).insert(customers);
}